### ISSUE TITLE
Publishing 3.1 compatible version?

### ISSUE THREAD

**Issue by sburnicki** [gpc/taggable#11]
Currently, I can't find this plugin on [Bintray](https://bintray.com/grails/plugins), only a snapshot from last year on [repos.grails.org](https://repo.grails.org/grails/core/org/grails/plugins/taggable/).
Travis [successfully builds](https://travis-ci.org/gpc/taggable) this plugin, but fails because of a missing configuration for publishing it.

Are there any publishing plans, so people with grails 3.1 can easily use this plugin?
A new snapshot releas on repos.grails.org would be sufficient. Is someone working on this?

The [OpenSpeedMonitor](https://github.com/IteraSpeed/OpenSpeedMonitor) depends on this plugin and people should really be able to get it from somewhere.

**Comment by sburnicki** [comment]
@graemerocher Are there plans?

**Comment by kboboli** [comment]
@graemerocher - same question. I am currently creating my very first app in Grails 3.1 and your plugin would be very useful for me.

**Comment by jeffbrown** [comment]
@sburnicki @kboboli @sburnicki Have you done testing with the published snapshots?

**Comment by kboboli** [comment]
@jeffbrown 
Hi, 
I successfully added the latest plugin snapshot to my app and did some testing - works fine (on Grails 3.1.4)
Thanks
Karolina

**Comment by markoschnecke** [comment]
@jeffbrown we've added the new dependency to the [OpenSpeedMonitor](https://github.com/IteraSpeed/OpenSpeedMonitor) and it seems to work as advertised. Out of curiosity: is a release of the new version of Taggable planned? Anyway thanks a lot for your help!

**Comment by sburnicki** [comment]
The [2.0.1 snapshot](https://repo.grails.org/grails/core/org/grails/plugins/taggable/2.0.1-SNAPSHOT/) from the grails repo is suffcient, thank you!

**Comment by graemerocher** [comment]
I reopened this because a 2.0.1 release needs to be done still

**Comment by codeconsole** [comment]
Can we get a 3.3.x release?  I put in a pull request.  Let me know if there are any other changes you would like.
https://github.com/gpc/taggable/pull/14
