### ISSUE TITLE
Taggable dependency not working 

### ISSUE THREAD

**Issue by romanye** [gpc/taggable#15]
This issue started happening yesterday and seems to be related to this alert: 
https://grails.org/blog/2021-02-12-alerts-regarding-bintray-sunset.html

```

> Could not resolve all dependencies for configuration ':runtime'.
   > Could not resolve org.grails.plugins:taggable:2.1.0-SNAPSHOT.
     Required by:
         chartertools:chartertools:4.1.0
      > Could not resolve org.grails.plugins:taggable:2.1.0-SNAPSHOT.
         > Unable to load Maven meta-data from http://dl.bintray.com/stefanogualdi/plugins/org/grails/plugins/taggable/2.1.0-SNAPSHOT/maven-metadata.xml.
            > Could not GET 'http://dl.bintray.com/stefanogualdi/plugins/org/grails/plugins/taggable/2.1.0-SNAPSHOT/maven-metadata.xml'. Received status code 403 from server: Forbidden
      > Could not resolve org.grails.plugins:taggable:2.1.0-SNAPSHOT.
         > Unable to load Maven meta-data from http://dl.bintray.com/agorapulse/libs/org/grails/plugins/taggable/2.1.0-SNAPSHOT/maven-metadata.xml.
            > Could not GET 'http://dl.bintray.com/agorapulse/libs/org/grails/plugins/taggable/2.1.0-SNAPSHOT/maven-metadata.xml'. Received status code 403 from server: Forbidden
```

We use the Taggable plugin in two different Grails projects (also different versionS). 
This error occurs when running Grails version 3.3.8 and JDK 8. 

Do we need to create a local dependency of this plugin?
If so, which version of the code should we use? The 2.1.0 version is nowhere to be found on github.

Any suggestions would be greatly appreciated since this is a critical plugin for this project.

**Comment by codeconsole** [comment]
https://github.com/grails/grails-core/issues/11825

**Comment by romanye** [comment]
Indeed, it was. 
Issue was resolved after following the workaround for Grails Core, creating a new app and slowly moving all the code artifacts to the new project. Thanks.
