### ISSUE TITLE
Trait not being applied to Java Domain classes

### ISSUE THREAD

**Issue by ryancornia** [gpc/taggable#8]
I have my domain classes as Java/JPA object. In Grails 2.5.2, the taggable plugin would correctly apply the trait to them. In 3.0.10 with this version of the plugin, I get compile errors that my domain objects that implement Taggable need to implement the methods defined in the trait.

I am not sure if this is a taggable code issue or grails 3.0.10? I believe the taggable code may need a trait interceptor?

**Comment by jeffbrown** [comment]
> I believe the taggable code may need a trait interceptor?

What do you mean by "trait interceptor"?

**Comment by jeffbrown** [comment]
> I have my domain classes as Java/JPA object. In Grails 2.5.2, the taggable plugin would correctly apply the trait to them.

I am not sure how that could have worked and I don't think the Grails 2 version of the plugin even had a trait.

**Comment by ryancornia** [comment]
It turns out a workaround is to have an abstract groovy domain object that implements taggable, then extend that in my java jpa objects. 

I am not familiar with groovy traits, but assumed they could be applied to java classes at compile time as well as groovy classes. It looks like probably not. Creating a groovy base class and extending it works and accomplishes the same thing, just not quite as elegantly. 

I am not sure how this worked in grails 2.x, it just worked out of the box by implementing taggable on my jpa objects.

**Comment by jeffbrown** [comment]
> I am not sure how this worked in grails 2.x, it just worked out of the box by implementing taggable on my jpa objects.

That is true.  I was addressing the original claim that in Grails 2.5.2 that the tangible plugin was applying a trait to Java/JPA objects.  That didn't (and couldn't) happen.
