### ISSUE TITLE
Upgrade to Grails 3.1.1

### ISSUE THREAD

**Issue by naman90** [gpc/taggable#9]
I am migrating 2.4.4 project to 3.1.1 and as discussed in  [9506](https://github.com/grails/grails-core/issues/9506) , @graemerocher  does this plugin needs to be compiled with 3.1.1 against GORM 5, so that there's no conflict?

Also documentation needs to be updated for its dependency to  -     compile "org.grails.plugins:taggable:2.0.0-SNAPSHOT".

**Comment by BirgerK** [comment]
we prepared a PR in #10 for updating taggable to Grails 3.1.5. Our application is already working with this branch.

It would be great if this PR would be accepted and the working version would be published to the repos.
